# NUMPY

In [6]:
import numpy as np

In [7]:
a = [1,2,3,4]
b = [5,6,7,8]

ab = []

for i in range(0,len(a)):
    ab.append(a[i]*b[i])
print(ab)

[5, 12, 21, 32]


In [8]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])
a*b

array([ 5, 12, 21, 32])

### Numpy Arrayi Oluşturmak

In [9]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [10]:
type(np.array([1,2,3,4,5]))

numpy.ndarray

In [11]:
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [14]:
np.random.randint(0,10,10)

array([0, 8, 9, 6, 4, 1, 8, 9, 1, 8])

In [16]:
np.random.normal(5,2,(3,4))

array([[5.3892724 , 4.75388417, 6.194292  , 5.37482215],
       [7.43551378, 1.31481429, 5.98098229, 4.64000748],
       [6.42216298, 7.06230308, 0.97669577, 7.48370927]])

### Numpy Array Özellikleri

In [17]:
a = np.random.randint(10, size = 5)
# ndim : boyut sayısı
# shape : boyut bilgisi
# size : toplam eleman sayisi
# dtype : array veri tipi 


In [21]:
a.ndim #Tek boyutlu.

1

In [22]:
a.shape

(5,)

In [23]:
a.size

5

In [24]:
a.dtype

dtype('int32')

### Reshaping (Yeniden Şekillendirme)

In [26]:
np.random.randint(1,10,9)
np.random.randint(1,10,9).reshape(3,3)

array([[5, 2, 6],
       [1, 1, 8],
       [2, 3, 9]])

### Index İşlemleri

In [27]:
a = np.random.randint(10,size = 10)

In [28]:
a

array([0, 3, 7, 1, 4, 0, 7, 4, 5, 6])

In [29]:
a[0]

0

In [30]:
a[0:4]

array([0, 3, 7, 1])

In [31]:
a[0] = 8

In [32]:
a

array([8, 3, 7, 1, 4, 0, 7, 4, 5, 6])

In [36]:
m = np.random.randint(10,size=(3,5))

In [37]:
m

array([[4, 2, 1, 6, 2],
       [6, 8, 3, 6, 6],
       [6, 6, 8, 4, 5]])

In [38]:
m[0,0]

4

In [39]:
m[0,:]

array([4, 2, 1, 6, 2])

In [40]:
m[2,2]

8

### Fancy Index

In [43]:
v = np.arange(0,30,3)

In [44]:
v

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [45]:
catch = [1,5,9]

In [46]:
v[catch]

array([ 3, 15, 27])

### Koşullu İşlemler

In [49]:
v[v<3]

array([0])

In [50]:
v[v>3]

array([ 6,  9, 12, 15, 18, 21, 24, 27])

In [51]:
v[v!=3]

array([ 0,  6,  9, 12, 15, 18, 21, 24, 27])

In [52]:
v[v==3]

array([3])

### Matematiksel İşlemler


In [53]:
v * 2

array([ 0,  6, 12, 18, 24, 30, 36, 42, 48, 54])

In [54]:
a = np.random.randint(10,size=(5,2))

In [55]:
a

array([[9, 8],
       [9, 8],
       [5, 3],
       [9, 7],
       [0, 2]])

In [57]:
a*2

array([[18, 16],
       [18, 16],
       [10,  6],
       [18, 14],
       [ 0,  4]])

### Matematiksel İşlemler

In [58]:
v = np.array([1,2,3,4,5])

In [59]:
v/5

array([0.2, 0.4, 0.6, 0.8, 1. ])

In [60]:
v+2

array([3, 4, 5, 6, 7])

In [61]:
np.subtract(v,1)

array([0, 1, 2, 3, 4])

In [63]:
np.add(v,1)

array([2, 3, 4, 5, 6])

In [64]:
np.mean(v)

3.0

In [65]:
np.sum(v)

15

In [67]:
np.min(v)

1

In [68]:
np.max(v)

5

In [70]:
np.var(v) #varyans

2.0

In [71]:
v = np.subtract(v,1)

In [72]:
v

array([0, 1, 2, 3, 4])

In [73]:
# 5*x0 + x1 = 12
# x0 + 3*x1 = 10 İki bilinmeyenli denklem çözümü 

In [75]:
a = np.array([[5,1],[1,3]])
b = np.array([12,10])

In [76]:
np.linalg.solve(a,b)

array([1.85714286, 2.71428571])